export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Home } from './Home'
export { default as Projects } from './Projects'
export { default as NotFound } from './NotFound'
export { default as ReposGitHub } from './ReposGitHub'
export { default as Footer } from './Footer'